---
title: "Lecture 18 (Linear Models)"
author: "CJ Snyder"
date: "11/7/2019"
output: html_document
---

```{r setup}
library(tidyverse)
library(knitr)
library(readxl)
library(viridis)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

library(p8105.datasets)
set.seed(1)
```

# **Model Fitting**
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit

summary(fit)

coef(fit)
summary(fit)$coef

```

## Tidy the results
```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```


# Take a look at factors...
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type)
  ) 
```

```{r}
fit = lm(price ~ stars + boro, data=nyc_airbnb)

fit %>% 
  broom::tidy()

fit %>% 
  broom::glance()
```


# **Diagnostics**
```{r}
modelr::add_residuals(nyc_airbnb, fit)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = boro, y = resid)) + geom_violin() +
  ylim(-500,500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point() +
  ylim(-500,500)
```
## **NOTES:** Violin plot is hard to see any distinction between observations' residuals...but you can see that the linear model is being skewed by the extremely large observations.

## _Predictions/Estimations_
```{r}
modelr::add_predictions(nyc_airbnb, fit)
```


# **Nesting Dataset**
```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

fit_interaction = lm(price ~ stars + boro + stars * boro, data = nyc_airbnb)

fit_interaction %>% 
  broom::tidy()
```


```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)

nest_lm_res
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  nest (data = -neighborhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data=.x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(results)
```

```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
nyc_airbnb %>% 
  filter(neighborhood=="NoHo", room_type=="Shared room")
```

Let's see if this works...







