---
title: "Lecture 19 (Linear Models II)"
author: "CJ Snyder"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(readxl)
library(viridis)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

library(modelr)
library(mgcv)
```

# **Cross Validation**
```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point() + theme_bw()
```

## Training and Testing
```{r}
train_df = sample_frac(nonlin_df, size = 0.80)

test_df = anti_join(nonlin_df, train_df, by="id")

ggplot(train_df, aes(x=x, y=y)) +
  geom_point() +
  geom_point(data=test_df, color="red")
```

## Fit three models of varying goodness
```{r}
linear_mod = lm(y~x, data=train_df)

smooth_mod = mgcv::gam(y~s(x), data=train_df)

wiggly_mod = mgcv::gam(y~s(x, k=30), sp=10e-6, data=train_df)
```

```{r}
train_df %>% 
  add_predictions(linear_mod) %>% 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  geom_point(aes(y=pred), color="red")

train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")

train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```


```{r}
rmse(linear_mod, test_df)

rmse(smooth_mod, test_df)

rmse(wiggly_mod, test_df)
```


# **Completing Cross Validation using _modelr_**
```{r}

```










